#!/bin/bash
cd $(dirname $(dirname $0)) || exit

mkdir .volumes/logs .volumes/problems .volumes/media .volumes/res

cp ../config.js repo/websocket/
cp ../local_settings.py repo/dmoj/
cp ../uwsgi.ini repo/
