version: '3.7'
services:
  # db:
    # container_name: dmoj_mysql
    # image: mariadb
    # restart: always
    # volumes:
      # - ./.volumes/database/:/var/lib/mysql/
    # env_file: [environment/mysql.env, environment/mysql-admin.env]
    # networks: [db]
  redis:
    container_name: dmoj_redis
    image: redis:alpine
    restart: always
    networks: [site]
  texoid:
    image: ninjaclasher/dmoj-texoid
    restart: unless-stopped
    networks: [site]
  mathoid:
    image: ninjaclasher/dmoj-mathoid
    restart: unless-stopped
    volumes:
      - ./mathoid/config.yaml:/node_modules/mathoid/config.yaml
    networks: [site]
  site:
    image: ninjaclasher/dmoj-site
    restart: unless-stopped
    volumes:
      - assets:/assets/
      - pdfcache:/pdfcache/
      - datacache:/datacache/
      - cache:/cache/
      - ./.volumes/logs/:/logs/
      - ./.volumes/media/:/media/
      - ./.volumes/problems/:/problems/
      - ./repo/:/site/
    working_dir: /site/
    user: 1000:1000
    env_file: [environment/mysql.env, environment/site.env]
    networks: [site, nginx]
    depends_on: [redis]
  celery:
    image: ninjaclasher/dmoj-celery
    restart: unless-stopped
    volumes:
      - datacache:/datacache/
      - ./.volumes/logs/:/logs/
      - ./repo/:/site/
    working_dir: /site/
    env_file: [environment/mysql.env, environment/site.env]
    networks: [site]
    depends_on: [redis]
  bridged:
    image: ninjaclasher/dmoj-bridged
    restart: unless-stopped
    volumes:
      - ./.volumes/logs/:/logs/
      - ./.volumes/problems/:/problems/
      - ./repo/:/site/
    working_dir: /site/
    env_file: [environment/mysql.env, environment/site.env]
    networks: [site, nginx]
    ports:
      - 9999:9999
    depends_on: [redis]
  wsevent:
    image: ninjaclasher/dmoj-wsevent
    restart: unless-stopped
    volumes:
      - ./repo/:/app/site/
    working_dir: /app/site
    networks: [site, nginx]
  nginx:
    container_name: dmoj_nginx
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - assets:/assets/
      - pdfcache:/pdfcache/
      - datacache:/datacache/
      - cache:/cache/
      - ./.volumes/logs/:/logs/
      # static files internally managed by web app
      - ./.volumes/media/:/media/
      # static files manually managed
      - ./.volumes/res/:/res/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks: [nginx]
    depends_on: [site, wsevent]
networks:
  site:
  nginx:
volumes:
  assets:
  pdfcache:
  datacache:
  cache:
